import React, { Component } from 'react';
import axios from 'axios';

class TransferForm extends Component {
    constructor(props) {
        super(props);
<<<<<<< HEAD
        this.state = {
            cardholderName: '',
            membershipNo: '',
            membershipNoConfirmation: '',
            transferAmount: ''
        };
    }

    handleSubmit = (event) => {
        event.preventDefault();
        const { cardholderName, membershipNo, membershipNoConfirmation, transferAmount } = this.state;

        if (membershipNo === membershipNoConfirmation) {
            const form = {
                cardholderName,
                membershipNo,
=======
            this.state = {
            membershipId: '',
            memberName: '',
            membershipIdConfirmation: '',
            transferAmount: ''
        };
    }
    
    // To return the current Date as a string
    getDate = () => {
        const currentDate = new Date();

        // To get date without time
        //currentDate.setHours(0, 0, 0, 0);
        
        // To keep only the date portion
        return currentDate.toISOString().split('T')[0];
    };
    
    
    // Returns true if membershipId is of correct format
    membershipValidation = (membershipId) => {
        // TODO 
        // Grab validation format from DB (After LoyaltyProgramQuery API is implemented)
        return true;
    };

    handleSubmit = (event) => {
        event.preventDefault();
        const { membershipId, memberName, membershipIdConfirmation, transferAmount } = this.state;

        const transferDate = this.getDate();

        if (membershipId === membershipIdConfirmation && this.membershipValidation(membershipId)) {
            const form = {
                membershipId,
                memberName,
                transferDate,
>>>>>>> 31fde4fdfac46053a7b5371bfe36a0a9852f4368
                transferAmount
            };
            
            console.log(form);

            axios.post('http://localhost:3001/api/transferFormSubmit', form)
                .then(response => {
<<<<<<< HEAD
=======
                    // TODO, save referenceNumber generated by TransferConnect app
>>>>>>> 31fde4fdfac46053a7b5371bfe36a0a9852f4368
                    console.log(response.data);
                })
                .catch(error => {
                    console.error(error);
                });
        }
        else {
<<<<<<< HEAD
            // TODO
=======
            // TODO if the membershipId is not valid or not of confirmation
>>>>>>> 31fde4fdfac46053a7b5371bfe36a0a9852f4368
            return;
        }
    }

    handleChange = (event) => {
        const { name, value } = event.target;
        this.setState({ [name]: value });
    }

    render() {
<<<<<<< HEAD
        const { cardholderName, membershipNo, membershipNoConfirmation, transferAmount } = this.state;
=======
        const { memberName, membershipId, membershipIdConfirmation, transferAmount } = this.state;
>>>>>>> 31fde4fdfac46053a7b5371bfe36a0a9852f4368

        return (
            <div>
                <form onSubmit={this.handleSubmit}>
<<<<<<< HEAD
                    <label htmlFor="cardholderName">PRIMARY CARDHOLDER</label>
                    <input
                        type="text"
                        id="cardholderName"
                        name="cardholderName"
                        value={cardholderName}
=======
                    <label htmlFor="memberName">PRIMARY CARDHOLDER</label>
                    <input
                        type="text"
                        id="memberName"
                        name="memberName"
                        value={memberName}
>>>>>>> 31fde4fdfac46053a7b5371bfe36a0a9852f4368
                        onChange={this.handleChange}
                    />
                    <br />

<<<<<<< HEAD
                    <label htmlFor="membershipNo">MEMBERSHIP #</label>
                    <input
                        type="text"
                        id="membershipNo"
                        name="membershipNo"
                        value={membershipNo}
=======
                    <label htmlFor="membershipId">MEMBERSHIP #</label>
                    <input
                        type="text"
                        id="membershipId"
                        name="membershipId"
                        value={membershipId}
>>>>>>> 31fde4fdfac46053a7b5371bfe36a0a9852f4368
                        onChange={this.handleChange}
                    />
                    <br />

<<<<<<< HEAD
                    <label htmlFor="membershipNoConfirmation">CONFIRM MEMBERSHIP #</label>
                    <input
                        type="text"
                        id="membershipNoConfirmation"
                        name="membershipNoConfirmation"
                        value={membershipNoConfirmation}
=======
                    <label htmlFor="membershipIdConfirmation">CONFIRM MEMBERSHIP #</label>
                    <input
                        type="text"
                        id="membershipIdConfirmation"
                        name="membershipIdConfirmation"
                        value={membershipIdConfirmation}
>>>>>>> 31fde4fdfac46053a7b5371bfe36a0a9852f4368
                        onChange={this.handleChange}
                    />
                    <br />

                    <label htmlFor="transferAmount">TRANSFER AMOUNT</label>
                    <input
                        type="text"
                        id="transferAmount"
                        name="transferAmount"
                        value={transferAmount}
                        onChange={this.handleChange}
                    />
                    <br />

                    <input
                        type="submit"
                        value="Submit"
                    />
                </form>
            </div>
        );
    }
}

export default TransferForm;
